### ISSUE TITLE
SPDX questions/bugs

### ISSUE THREAD

**Issue by rnjudge** [eBay/sbom-scorecard#22]
Hello! In playing with this tool a bit for Tern reports I have a couple questions and small bugs:

Questions:
1) Does this tool ingest SPDX Tag value format or only JSON? I generated the same SBOM in both formats and only JSON format seemed to register anything in the scorecard tool.

2) Does the tool use `LicenseConcluded` or `LicenseDeclared` in its license calculation score? In my experimentation it appears to be using only Concluded (I would argue the tool should be calculating "declared" vs "concluded")

3) Does this tool count `LicenseRefs` as licenses in the license score or only SPDX License Identifiers?

4) If there are no files present in the SPDX document, should the "file digest" score still be 0 (vs some sort of NA score)?

Bugs:
1. Licenses do not seem to be properly accounted for in the license calculation score (maybe this is because it's only looking at concluded instead of declared?). In Tern's `photon:3.0` container image SBOM (SPDX json format), there are 38 packages. 25 packages have a `LicenseRef` value as the license concluded, 11 have an actual SPDX License identifier value and 2 are `NOASSERTION` yet scorecard says the report has 0% licenses found:
```
Guessed: spdx
38 total packages
0% have licenses.
==
Package Licenses: 0/20
```

2. Package version score does not correspond to the % of package versions found? Am I misunderstanding what the correlation should be? If 97% have versions then shouldn't the package version score be higher? Additionally, the 97% score seems to be incorrect. Out of 38 packages, all have a version provided so I'm not sure where 97% is coming from.
```
Guessed: spdx
38 total packages
97% have package versions.
==
Package Versions: 0/20
```

**Comment by rnjudge** [comment]
[photon.json.txt](https://github.com/eBay/sbom-scorecard/files/10406591/photon.json.txt) - test JSON file for reference (renamed to .txt to make GitHub happy)

[photon.spdxtv.txt](https://github.com/eBay/sbom-scorecard/files/10406598/photon.spdxtv.txt) - tag value version of same container

**Comment by justinabrahms** [comment]
Thanks for this issue!

To answer your questions:

1. Tag values are intended to be supported. It is/was hard to find a real one in the wild, so I'll use the one you've attached here as a test case. Thank you.
2. I think I'm fine with using both, with a preference for declared.
3. I don't know if it counts LicenseRefs (probably not), but I agree that it should.
4. If a section isn't applicable, you shouldn't get a zero for it. You should get max points.

I'll probably split your other things into bug tickets and reference them back here.

**Comment by rnjudge** [comment]
> Thanks for this issue!
> 
> To answer your questions:
> 
>     1. Tag values are intended to be supported. It is/was hard to find a real one in the wild, so I'll use the one you've attached here as a test case. Thank you.
> 
>     2. I think I'm fine with using both, with a preference for declared.
> 
>     3. I don't know if it counts LicenseRefs (probably not), but I agree that it should.
> 
>     4. If a section isn't applicable, you shouldn't get a zero for it. You should get max points.
> 
> 
> I'll probably split your other things into bug tickets and reference them back here.

Thank you! As @jspeed-meyers pointed out, I think the the package version percentage calculation is correct, just the final score (0/20) is off :)

**Comment by justinabrahms** [comment]
Alright. I believe that all of these, except #25 are addressed. Please open additional bugs if you find any and sorry for the delay in getting to these.
