### ISSUE TITLE
tag-value documents not parsing properly

### ISSUE THREAD

**Issue by justinabrahms** [eBay/sbom-scorecard#25]
The tag-value file shared in #22 doesn't parse, but it should.

**Comment by justinabrahms** [comment]
This is blocked on https://github.com/spdx/tools-golang/issues/182

**Comment by jspeed-meyers** [comment]
https://github.com/spdx/tools-golang/issues/182 is resolved. Should this issue be closed? Or is there work within `sbom-scorecard` that needs to be done?

**Comment by justinabrahms** [comment]
The things that need to happen:
1. https://github.com/spdx/tools-golang/ needs to make a release bigger than 0.4.0
2. we need to take a dependency on it
3. we need to validate that `go run ./cmd/... score ~/Downloads/photon.spdxtv.txt` runs and shows relevant package data, etc.
4. make a release.

**Comment by justinabrahms** [comment]
spdx is planning to bump their library at the end of this month.

**Comment by justinabrahms** [comment]
This was fixed in https://github.com/justinabrahms/sbom-scorecard/commit/8a5d858602713c89730f8e239efbb40f487dda1c 

cc @rnjudge
