### ISSUE TITLE
BUG: Dividing Integers by Integers Leads to Incorrect Score Calculation

### ISSUE THREAD

**Issue by jspeed-meyers** [eBay/sbom-scorecard#28]
In issue #22, it was pointed out that: 

> Package version score does not correspond to the % of package versions found? Am I misunderstanding what the correlation should be? If 97% have versions then shouldn't the package version score be higher? 

After some testing, the bug seems to be here:

https://github.com/eBay/sbom-scorecard/blob/c3d4dd80a6bacca380be7f73be257ebff66895bd/pkg/spdx/spdx_report.go#L74-L84

Line 82 should be:

```go
Ratio: float32(r.hasPackVer)  / float32(r.totalPackages),
```

Dividing an integer by an integer leads to zero, which is not the intended behavior, IIUC.

Here is a small snippet of Go code (in the Go Playground) explaining this bug: https://go.dev/play/p/gybFsSduxZa

Proposal: Fix all `Ratio:` lines to use the proper division in which both numbers are converted to a `float32`. This fix will encompass more than just the "package version" logic. I'm glad to put in a PR. Just LMK.

**Comment by justinabrahms** [comment]
PR welcome, @jspeed-meyers. Thanks for the debugging.
