### ISSUE TITLE
Consider Alternative Identifier Logic Related to purl and CPEs

### ISSUE THREAD

**Issue by jspeed-meyers** [eBay/sbom-scorecard#36]
One of the open questions at the bottom of the README asks:

> Should we preference towards purls or CPEs? Both?

After considering this question and doing some related (but not definitive) research, I would like to suggest two options.

Option 1: `sbom-scorecard` logic related to package IDs requires EITHER a purl or a CPE. Right now, the logic, IIUC, requires that each package contain both a purl and a CPE and otherwise that SBOM receives a lower score.

Option 2: Prefer purl only. Remove any requirement for CPE. If necessary, add an option logic to search for CPEs. To be clear, this option would not penalize the presence of CPEs. There would simply be no points awarded for CPEs.

I think option 1 is less likely to generate debate and dissent. Option 2, in the eyes of purl supporters, might be better for the long-term utility of SBOMs.

I think a short-term plan is to embrace option 1. I'm glad to put in a PR that changes the logic and test suite.

**The WHY of This Proposal**

[package URLs](https://github.com/package-url/purl-spec) are arguably superior to [CPEs](https://nvd.nist.gov/products/cpe) for identifying accurately open source software packages. Because most modern software is [mostly ](https://mergebase.com/MSR-2022/2022-MSR-Is-Open-Source-Eating.pdf)open source software, SBOM quality tools ought to prefer component naming schemes that are well-suited to open source software packages. A recent [report](https://owasp.org/assets/files/posts/A%20Proposal%20to%20Operationalize%20Component%20Identification%20for%20Vulnerability%20Management.pdf) provides a detailed theoretical and technical explantation of this argument. Preliminary [research](https://www.chainguard.dev/unchained/a-purl-of-wisdom-on-sboms-and-vulnerabilities) that I conducted corroborates the claim that package URLs can aid SBOM users by providing a more accurate naming scheme.

Other perspectives, arguments, and evidence are welcome :)

**Comment by rnjudge** [comment]
I don't not think PURLs are the silver bullet we want them to be but I agree that not having CPEs and PURLs shouldn't lower the score. I would personally prefer to see option 1 (EITHER purl or CPE).

**Comment by nscuro** [comment]
As this is specifically about *software* bill of materials, I'd prefer option 2. It would be a different story for BOMs in general, where hardware support must be considered.

As stated in the [report](https://owasp.org/assets/files/posts/A%20Proposal%20to%20Operationalize%20Component%20Identification%20for%20Vulnerability%20Management.pdf) @jspeed-meyers linked, it is almost impossible to get the CPE right, which means it's oftentimes not present in SBOMs, or plain wrong. Generators have to make educated guesses or provide multiple CPEs in various permutations, hoping that at least one of them is correct. None of that is really helpful on the consumer side.

If this tool gets traction, and generation tools are benchmarked against it, I'd hate to see CPE fields being populated just to get a higher score. Providing no CPE over a guessed CPE is more often than not an active decision that should not be punished.
