### ISSUE TITLE
BOM Maturity Model

### ISSUE THREAD

**Issue by stevespringett** [eBay/sbom-scorecard#4]
First off, thanks for this project. A scoring mechanism is a welcome addition that the sbom community will benefit from.

I wanted to draw attention to some related work in the [OWASP Software Component Verification Standard](https://scvs.owasp.org/). The group has been working towards defining a formalized taxonomy of BOM data along with profiles that would allow orgs to specify what data is important to them. We’re fairly far along in defining the taxonomy. We’re now starting to codify it. If you’d like to contribute to the [BOM Maturity Model](https://scvs.owasp.org/bom-maturity-model/), it’s open for anyone to [participate](https://scvs.owasp.org/participate/).

**Comment by justinabrahms** [comment]
Love that, @stevespringett. I'm also happy to have this tool eventually grow into a "you tell us the weights your company wants to put on the components, and we'll score the sboms for you" sort of thing.

**Comment by stevespringett** [comment]
Update from the SCVS project. We are expecting the MVP of the BOM Maturity Model to be available late Q1. There are two schemas:
* Model/taxonomy: this is the entirety of the maturity model
* Profile: this is what parts of the model a stakeholder or organization cares about and the weighted importance of each

Once we get drafts of the two schemas in place, I'll update this ticket again.

**Comment by justinabrahms** [comment]
Closing, but feel free to re-open if you feel there's any action to take on my part.
