### ISSUE TITLE
[Feature Request] Auto-Detect SBOM Format

### ISSUE THREAD

**Issue by jspeed-meyers** [eBay/sbom-scorecard#8]
I'm interested in using this tool on a set of SBOMs of mixed format types, some SPDX and some cyclonedx. For now I can sort these two different types into different folders and then use the right switch, but it would be easier if `sbom-scorecard` could check the format type first. I could imagine users wanting to run this tool on a large set of SBOMs and not having any indication which format each SBOM is.

Perhaps there could be an `auto` option for `--sbomtype` that then leads to some logic that first detects the type?

(Great tool, BTW!)

**Comment by justinabrahms** [comment]
Shortly after you filed this ticket, I added the "guess" type, which will do a best effort to do this detection. 

https://github.com/eBay/sbom-scorecard/blob/main/cmd/sbom-scorecard/cmd/scorecard.go#L31
